### ISSUE TITLE
Should we keep non-ZKP algorithms

### ISSUE THREAD

**Issue by dwaite** [ietf-wg-jose/json-web-proof#103]
Per discussion in IETF 118 microphone comments, should we keep algorithms which do not have a reasonably inexpensive nonsinkable presentation.

**Comment by selfissued** [comment]
Being able to represent and use non-ZKP algorithms is a forcing function that we're writing the specifications in widely-applicable manner.  That doesn't mean that, in the end, we need to have the single-use algorithms be REQUIRED or even RECOMMENDED.  But I'm loathe to rip them out now, because having multiple algorithms and multiple kinds of algorithms will help keep us honest.

**Comment by selfissued** [comment]
Per discussions at IETF 120 in Vancouver, it makes sense to keep several algorithms in the specs to ensure that the representations we're using are flexible and general-purpose.
